### ISSUE TITLE
[advice] Keep the text on the front page and in "issues" in English if you want a wide adoption of your project

### ISSUE THREAD

**Issue by yurivict** [mdevaev/emonoda#55]
Otherwise people just can't know what it is and what are you taking about.

**Comment by mdevaev** [comment]
I do not think that makes sense.
1) This is my pet project, which I do first of all for myself. I don't support any English torrent trackers myself, only Russian, which I use myself. Yes, it's looks like an enterprise system, but first of all it's a tool for solving my personal tasks. I don't have the strength and desire to support the active development of this project.
2) In addition to translating the README page, I need to translate the wiki and all other documentation so that people can use this system. This is a huge amount of work, and I don't want to translate everything into English myself.

**Comment by yurivict** [comment]
Arch Linux has a package. So it is everybody's project now. :D

**Comment by mdevaev** [comment]
It's my package lol :D

**Comment by yurivict** [comment]
Whatever.
